### @{{$processEnv process environment variable name}}



### GET ALL SHOWS at ONCE in HOME
GET {{SERVER_URL}}/all?search=gold&limit=100&offset=0&userid=3
Authorization: Bearer 


### POST method For SignUp
POST {{SERVER_URL}}/signup/
Content-Type: application/json

{
    "username":"",
    "password":"",
    "email":""
}

### POST method For Login
POST {{SERVER_URL}}/login/
Content-Type: application/json

{
    "username":"",
    "password":""
}

### GET method for kysLogo

GET {{SERVER_URL}}/kyslogo/


### GET method for Top Telugu
GET {{SERVER_URL}}/toptelugu/
Authorization: Bearer 

### GET method for Top Telugu
GET {{SERVER_URL}}/tophindi/
Authorization: Bearer 

### GET method for Top Telugu
GET {{SERVER_URL}}/topenglish/
Authorization: Bearer 